#!/usr/bin/env bash

set -euo pipefail

while getopts ":p:a" opt; do
  case "$opt" in
    a)
      PUSH_ALL_BRANCHES=true >&2
      ;;
    p)
      BUILDKITE_PIPELINE_SLUG=$OPTARG >&2
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
    ?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

NAME="docker-dev-artifactory.workday.com/peakon/${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}"
echo ${NAME}

docker build -t ${NAME}:${BUILDKITE_BRANCH}-latest .
docker build -t ${NAME}:${BUILDKITE_BRANCH}-${BUILDKITE_COMMIT} .

if [[ "${BUILDKITE_BRANCH}" =~ ^(master)$ || -n "${PUSH_ALL_BRANCHES:-}" ]]; then
  echo "--- Push Docker image to Artifactory"
  docker push "${NAME}:${BUILDKITE_BRANCH}-latest"
  docker push "${NAME}:${BUILDKITE_BRANCH}-${BUILDKITE_COMMIT}"
  echo -e "Pushed tag: \033[33m${NAME}:${BUILDKITE_BRANCH}-latest\033[0m"
  echo -e "Pushed tag: \033[33m${NAME}:${BUILDKITE_BRANCH}-${BUILDKITE_COMMIT}\033[0m"
else
  echo "Skipped pushing docker images to ECR for branch: ${BUILDKITE_BRANCH}"
fi
