#!/usr/bin/env bash

set -euo pipefail

while getopts ":p:a" opt; do
  case "$opt" in
    a)
      PUSH_ALL_BRANCHES=true >&2
      ;;
    p)
      BUILDKITE_PIPELINE_SLUG=$OPTARG >&2
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
    ?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done

NAME="public.ecr.aws/${BUILDKITE_ORGANIZATION_SLUG}/${BUILDKITE_PIPELINE_SLUG}"

docker build --build-arg -t ${NAME}:latest .
docker build --build-arg -t ${NAME}:${BUILDKITE_COMMIT}

if [[ "${BUILDKITE_BRANCH}" =~ ^(master)$ || -n "${PUSH_ALL_BRANCHES:-}" ]]; then
  echo "--- Push Docker image to ECR"
  docker push "${NAME}:latest"
  docker push "${NAME}:${BUILDKITE_COMMIT}"
  echo -e "Pushed tag: \033[33m${NAME}:latest\033[0m"
  echo -e "Pushed tag: \033[33m${NAME}:${BUILDKITE_COMMIT}\033[0m"
else
  echo "Skipped pushing docker images to ECR for branch: ${BUILDKITE_BRANCH}"
fi
